### ISSUE TITLE
I think this error is because I have no angular code in my app

### ISSUE THREAD

**Issue by MichaelJCole** [Kagami/gulp-ng-annotate#23]
Hey, copied a gulpfile.js from one project to a new one.

Ran it before coding and got this error.  I think its because I have no angular code in my app yet.

```

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error in plugin 'gulp-ng-annotate'
app.js: error: couldn't process source due to parse error
Unexpected token (16:4)
    at transform (/home/michael/scm/wmw_www/node_modules/gulp-ng-annotate/index.js:20:11)
    at Transform._transform (/home/michael/scm/wmw_www/node_modules/gulp-ng-annotate/index.js:68:25)
    at Transform._read (/home/michael/scm/wmw_www/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/home/michael/scm/wmw_www/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/michael/scm/wmw_www/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/michael/scm/wmw_www/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/home/michael/scm/wmw_www/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/home/michael/scm/wmw_www/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/michael/scm/wmw_www/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/home/michael/scm/wmw_www/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
```

**Comment by Kagami** [comment]
The same as #21: it's an error in your source code:
```
app.js: error: couldn't process source due to parse error
Unexpected token (16:4)
```

I think I should create an FAQ entry about this kind of errors :)

**Comment by MichaelJCole** [comment]
Hey, yes!  Thanks for lookin at it :-)
